# Generated by Django 3.1.7 on 2021-03-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210312_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='manage',
            field=models.CharField(max_length=60),
        ),
    ]
